version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.1
    environment:
      SERVER_NAME: esnet
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
    ports:
      - 5601:5601
    networks:
      - esnet

  php:
    image: krizius/pilulka-php-apache
    volumes:
      - .:/var/www
    environment:
      XDEBUG_CONFIG: 'remote_enable=0'
    ports:
      - 26666:80
    networks:
      - esnet

  swagger_mock:
    image: swaggermock/swagger-mock
    environment:
      SWAGGER_MOCK_SPECIFICATION_URL: /app/documentation/pets.yaml
    ports:
      - "25555:8080"
    volumes:
      - ./docker/swagger:/app/documentation
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
